export DATABASE_URL='postgres://postgres:postgres1@localhost:5432/datadb'
export TESTDATABASE_URL='postgres://postgres:postgres1@localhost:5432/test_db'
export AUTH0_DOMAIN='datarithms.us.auth0.com'
export API_AUDIENCE='datarithms'
export ALGORITHMS='RS256'
